#!/bin/bash
# find directory of the app python script
HERE="$(dirname "$(readlink -f "${0}")")"
# update path to include any necessary directories
export PATH="${HERE}/usr/bin/IdleBot/bin:$PATH"
#execute python script
exec python "${HERE}/usr/bin/bot.py"